### ISSUE TITLE
Download says the version is for a newer version of brackets but I have the latest.

### ISSUE THREAD

**Issue by joaomcarlos** [Brackets-Themes/Railcasts#3]
Hello.

I am trying to download and install this theme, but when I try to do so, it says I need a newer version of brackets.

I updated my Brackets to the latest (as of today is "sprint 41 experimental build 0.41.0-13418 (release e642284b3) build timestamp: Thu Jun 26 2014 10:52:39 GMT-0700") and I still cannot install this theme.

What version of brackets is this created for?

**Comment by MiguelCastillo** [comment]
This theme along with the other themes https://github.com/Brackets-Themes are all intended to run in 42, which is shipping its own theme manager.
